name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    permissions:
      contents: write
      packages: write
    uses: simplyRoba/.github/.github/workflows/rust-publish-release.yml@e387ed580251a5623f32c0ab648a108e2b9ef8dc
    with:
      binary-name: gazel
