name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    permissions:
      contents: write
      packages: write
    uses: simplyRoba/.github/.github/workflows/rust-publish-release.yml@b81ec038c117de33290ae28fd4185c2763a1fbc8
    with:
      binary-name: gazel
