name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: read
    uses: simplyRoba/.github/.github/workflows/rust-release-please.yml@e387ed580251a5623f32c0ab648a108e2b9ef8dc
    secrets: inherit
