name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: read
    uses: simplyRoba/.github/.github/workflows/rust-release-please.yml@b81ec038c117de33290ae28fd4185c2763a1fbc8
    secrets: inherit
